### ISSUE TITLE
API: renaming const and import

### ISSUE THREAD

**Issue by yorkie** [yorkie/tensorflow-nodejs#10]
As @ry mentioned:

> "import" and "const" are keywords in JS, so I think "graph.import" and "graph.const" are undesirable choices.

Now a propose is that:

- use `constant` instead of `const` by keeping consistence with Python
- use `load` or other name not in keywords list should address this issue basically

Hi @ry this looks good to you?

**Comment by ry** [comment]
Yes, those are good alternatives.
