### ISSUE TITLE
feature: support expression function

### ISSUE THREAD

**Issue by yorkie** [yorkie/tensorflow-nodejs#2]
JavaScript language doesn't have operator overloading, then that we could not bypass to do this like Python or C++:

```js
graph.matmul(x, W) + b
```

Currently only this way is working at Node.js library:

```js
graph.add(graph.matmul(x, W), b)
```
The ideal solution for current JavaScript standard is we wrap a function where we use the expression to represent what it is stand in math like this:

```js
session.run(function() {
  graph.matmul(x, W) + b;
});
```
And we now could use [esprima](https://github.com/jquery/esprima) to parse the function body and overload the operator in runtime.

**Comment by yorkie** [comment]
Another acceptable way to me is:

```js
graph.expr('graph.matmul(x, W) + b', x, W, b)
```
Parse the simpler expression not the complete statements or block, and map the undefined variables `x`, `W` and `b` from the rest arguments of this calls.

**Comment by ry** [comment]
I wouldn't worry about this...  `g.add(g.matmul(x, W), b)` is fine.

**Comment by yorkie** [comment]
Ok, let's keep it :)

**Comment by zixia** [comment]
How about this:

```js
x.matmul(W)
  .add(b)
```

Because this looks functional and feels more readable.

The downside is that this does not look like a formula in math.

**Comment by yorkie** [comment]
> The downside is that this does not look like a formula in math.

Hi @zixia This might be the answer, I'm going to make a plugin way to make this API could be extended by third-party libraries, user could choose which are comfortable, and the default is the current way.

**Comment by yorkie** [comment]
Just close this, let's keep current implementation.
