### ISSUE TITLE
Error: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-win32-x86_64-1.2.1.tar.gz Not Found

### ISSUE THREAD

**Issue by wangchaoduo** [yorkie/tensorflow-nodejs#26]
I use command 'npm install tensorflow2 --save' in windows ,but it throw an error,
I don't have root access in this computer

**Comment by yorkie** [comment]
Good catch, the windows download url is not valid!

**Comment by wangchaoduo** [comment]
o(╯□╰)o

**Comment by yorkie** [comment]
Reopened this because not resolved
