### ISSUE TITLE
looking for sample with simple image identification according to model and labels

### ISSUE THREAD

**Issue by Benz-Tracxpoint** [yorkie/tensorflow-nodejs#31]
My inputs are:
1 - model file
2 - labels file
3 - image
(All in the form of file links)
The output i would like to get is simply the best result and its percents Any suggestions or samples?

**Comment by yorkie** [comment]
Could you please fix the following https://github.com/yorkie/node-naoqi/blob/master/src/socket.js#L4:

```js
import * as SocketIO from 'socket.io-client';
```

**Comment by yorkie** [comment]
Do you accept the input to be a predefined or trained graph/model?

**Comment by Benz-Tracxpoint** [comment]
yes, I have a graph.pb, labels.txt, img.png all are ready to be tested together

**Comment by yorkie** [comment]
The v1 is deprecated and I'm rewriting the v2, it's based on Python tensorflow package, so this might be resolved :)
